<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Apibim.Revit.Extensions</AssemblyName>
    <RootNamespace>Apibim.Revit.Extensions</RootNamespace>
    <Version>$(RevitVersion).0.1</Version>

    <!-- NuGet metadata -->
    <PackageId>Apibim.Revit.Extensions</PackageId>
    <Authors>Apibim</Authors>
    <Company>Apibim.com</Company>
    <Description>Extension methods for Autodesk Revit API</Description>
    <RepositoryUrl>https://github.com/apibim/Revit.Extensions</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3"
        Condition="'$(TargetFramework)' != 'net8.0-windows'" />
  </ItemGroup>

</Project>
